### ISSUE TITLE
Info Requested

### ISSUE THREAD

**Issue by nitin20212** [awsdocs/amazon-lex-developer-guide#10]
Is there a way to overwrite user utterance in Lex ? or Define Generic Intent which will accept user utterance as is and pass to the next level ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
