### ISSUE TITLE
Inaccurate Documentation for AMAZON.DATE

### ISSUE THREAD

**Issue by orenely** [awsdocs/amazon-lex-developer-guide#12]
This [description of AMAZON.DATE](https://github.com/awsdocs/amazon-lex-developer-guide/blob/master/doc_source/built-in-slot-date.md) does not accurately describe how the slot type currently operates.  It says the system will resolve all date inputs as specific calendar dates, regardless of what type of date the user specifies. For example:
- "today" = 2020-05-05,
- "April 2017" = 2017-04-30,
- "2016" = 2016-12-31.

The actual current behavior is more in line with what is described in the [Alexa skill documentation](https://developer.amazon.com/en-US/docs/alexa/custom-skills/slot-type-reference.html#date).  This resolves to:
- "today" = 2020-05-05
- "April 2017" = 2017-04
- "2016" = 2016

Does this page reflect an upcoming change? If so, we need to know about it because it would cause breaking changes in the application we are currently developing.

**Comment by cbigham** [comment]
The behavior of the AMAZON.DATE built-in slot type changed when we introduced accuracy improvements on August 6th. There is a blog post about the accuracy improvements here: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-lex-launches-accuracy-improvements-and-confidence-scores/

For the regions listed below you need to opt-in to enable accuracy improvements. In the console, choose confidence scores in the Advanced Options section. Using the API, set the enableModelImprovements parameter when you call the PutBot operation.

- US East (N. Virginia) (us-east-1)
- US West (Oregon) (us-west-2)
- Asia Pacific (Sydney) (ap-southeast-2)
- Europe (Ireland) (eu-west-1)

In all other regions, accuracy improvements are available by default.
