### ISSUE TITLE
Fixing a minor typo in lambda-input-response-format.md

### ISSUE THREAD

**Issue by behnam354** [awsdocs/amazon-lex-developer-guide#6]
In this documentation:

https://github.com/awsdocs/amazon-lex-developer-guide/blob/master/doc_source/lambda-input-response-format.md

Change "a entry" to "an entry".

Cheers,
Behnam

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
